[[OpenSSL]]
arch = "aarch64"
git-tree-sha1 = "556f6f60b7da1c3e3d459b4dd42ad742ddf7d2fe"
os = "macos"

    [[OpenSSL.download]]
    sha256 = "13266d089e0a32f623289c1f7b706fe86cd559392940a9f2578f67e47d49b689"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.aarch64-apple-darwin.tar.gz"
[[OpenSSL]]
arch = "aarch64"
git-tree-sha1 = "b9bf70ec6a5346bdb858ce7680e416aeda6a67cd"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "8559d4bd8eda4e4b7cd99b66824d39f946d69ba90bb99899c258d2e8d10cea90"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.aarch64-linux-gnu.tar.gz"
[[OpenSSL]]
arch = "aarch64"
git-tree-sha1 = "b74c225bd7930d901635cc890987aec04dc3824f"
libc = "musl"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "d2d4bce7d1fb7910c809ebdcb7e707610a5f5fd5c58f81e4e676eb3cd52e8325"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.aarch64-linux-musl.tar.gz"
[[OpenSSL]]
arch = "aarch64"
git-tree-sha1 = "2330b9b13321f80b4efe8aea824705ebef447324"
os = "freebsd"

    [[OpenSSL.download]]
    sha256 = "9b1239175c5cb2b9b570c0acf36e6684346e5ee4c7b2af53ca11aaa5b761fe8a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.aarch64-unknown-freebsd.tar.gz"
[[OpenSSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c04feb80f93c626e95516de2addc8bd02ac4ba56"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "e82c39237fc464f6542a27aff9aa1b355a5dce07355eed8e4b32a1b358992b6f"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7c7a185d411c76aa4dc9a9cae5a54fb9726f3013"
libc = "musl"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "8eb6300ed6a2eb63e322ab3af2bfec429ee851ef2486decdcfd4b0b803976dc5"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.armv6l-linux-musleabihf.tar.gz"
[[OpenSSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2959b4a08de4baa8cc7d2bc9f75aea393bdd122"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "58781670be8c8bce989425a69117b551a258cac68fbc6f277a1e5c09ed9415b4"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "32216789fc27af1a0ba57adfaf8bfbb34bfd8402"
libc = "musl"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "52db8cf5e8f9bc37ac5d3ff521e55cb2f7cb6b005043f8e71495e2d503e2a985"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.armv7l-linux-musleabihf.tar.gz"
[[OpenSSL]]
arch = "i686"
git-tree-sha1 = "5e8eb7f30f34a7aa75509ae84b1ffc620b390b02"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "9f28fb7739594173f6a0056e7f66cf79bdc8f10403d71430300e324205f1b3a8"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.i686-linux-gnu.tar.gz"
[[OpenSSL]]
arch = "i686"
git-tree-sha1 = "d7863594af95a9aacadfbcd866be35f8a39c0da0"
libc = "musl"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "1f5ffc778cf89a178451f3daeedac9e264ad380fdcb1020c3964ba35673a7c15"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.i686-linux-musl.tar.gz"
[[OpenSSL]]
arch = "i686"
git-tree-sha1 = "3fd6146f44ea3476cc1f863ec0449df66913fb6d"
os = "windows"

    [[OpenSSL.download]]
    sha256 = "7524f13ee069b5aafbdab4cf1433b42f5c75ab454456e1722ed344768f2ed4b5"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.i686-w64-mingw32.tar.gz"
[[OpenSSL]]
arch = "powerpc64le"
git-tree-sha1 = "ca71ee30ac2c865dbb3570dbb90aa79311303f78"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "fb012c3d2070d63e34448ee5928328a3613482ce5227061bedb4a1e9b1e84350"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.powerpc64le-linux-gnu.tar.gz"
[[OpenSSL]]
arch = "riscv64"
git-tree-sha1 = "9159225e9bb32e75ca3b01e4a3d12e383eab77a8"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "cc28ecdcf81fcdaff843807ccd13d38ad660a2c6b3b208b002ed40e6cceda37f"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.riscv64-linux-gnu.tar.gz"
[[OpenSSL]]
arch = "x86_64"
git-tree-sha1 = "0be8b40b31a6d23412f08790c2e08b5c8a0241be"
os = "macos"

    [[OpenSSL.download]]
    sha256 = "a83d1c966f123b174f247ccbda0e424b3b52597c92086246e321a8b5d20c78b2"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.x86_64-apple-darwin.tar.gz"
[[OpenSSL]]
arch = "x86_64"
git-tree-sha1 = "b65de8f08b9b5060cdfcbf9cc01307ca933faaa2"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "db2569022a4de9ba043241c09fa9a22ba154e3d6dcd57df12de72a56b9deb73a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.x86_64-linux-gnu.tar.gz"
[[OpenSSL]]
arch = "x86_64"
git-tree-sha1 = "885696ea9e25ec7bacc6b22c112a6f712f547d1b"
libc = "musl"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "30ec4bb39aea74336a92713216c1948f3e0cb2cc93e14d373c66a8b8fd2d3d15"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.x86_64-linux-musl.tar.gz"
[[OpenSSL]]
arch = "x86_64"
git-tree-sha1 = "ae2cd403ec81b69d25198c0819286a73bc45ead5"
os = "freebsd"

    [[OpenSSL.download]]
    sha256 = "9f93d9525f88636e9bace2e48bc92afed3a2c05653b6fd0c8a3856ca06ed4d82"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.x86_64-unknown-freebsd.tar.gz"
[[OpenSSL]]
arch = "x86_64"
git-tree-sha1 = "789cc4df41084c795d4cf78f01068db1a5e06c7f"
os = "windows"

    [[OpenSSL.download]]
    sha256 = "45889a15f2a88e47ff8d3b70983f6171ea0e0be883e1f232e0b8666f9c17abe3"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.8+0/OpenSSL.v3.5.8.x86_64-w64-mingw32.tar.gz"
