[[OpenSSL]]
arch = "aarch64"
git-tree-sha1 = "cabba30af6b070cf45fcc91d4a9204fb2fa5039d"
os = "macos"

    [[OpenSSL.download]]
    sha256 = "c032656be399deea6e144baa7e24fa1105eeaf9cec94279c1de685adb94bc52d"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.aarch64-apple-darwin.tar.gz"
[[OpenSSL]]
arch = "aarch64"
git-tree-sha1 = "f40234607b0d581255322371bfabfa18c9215635"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "066a40cee76b28acb6781d01d0354a2e3f7b0514c856e3ca953f48fe6b217a59"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.aarch64-linux-gnu.tar.gz"
[[OpenSSL]]
arch = "aarch64"
git-tree-sha1 = "e028f9149ef6b6cf51dff063ab91ded413b73932"
libc = "musl"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "cb080dfd722dea5f1a31b8ad479145a8bfc5e5b398ed7932907f98956e7ce270"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.aarch64-linux-musl.tar.gz"
[[OpenSSL]]
arch = "aarch64"
git-tree-sha1 = "4f06998f8149be14003c808917b75f9cbd101c0c"
os = "freebsd"

    [[OpenSSL.download]]
    sha256 = "f9c41808a4c983ece63ed484f28e008e0b0c69dd50b4d783cdca3b7507679710"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.aarch64-unknown-freebsd.tar.gz"
[[OpenSSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "45ecd8aa6ec503f256a7e9bb707780855f1cff0b"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "55cc24b1ebcbcacec44a893d8c567778b626fb4b2c8f699a9156b37a1ff18857"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.armv6l-linux-gnueabihf.tar.gz"
[[OpenSSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3c223abb6cd688837138971349746a60b8f8e42b"
libc = "musl"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "a4de63915761ff0126bd97f2e59fc35810a57412a9a9d335ebec53abfcbd5686"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.armv6l-linux-musleabihf.tar.gz"
[[OpenSSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7e588e2af4c4b5ff211cae8504032bb07cc4fa9c"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "cc93c5bee00f0ca0cccf62e1755b1e5d60313bc749926a1130926c7379e4f17d"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.armv7l-linux-gnueabihf.tar.gz"
[[OpenSSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "36ad3e79d49e0a307a88737ca79362efbe53a59b"
libc = "musl"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "64359d95974dd43660e4fae041be505119f9cef65e1d15e89cc0b8fb70caf3a1"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.armv7l-linux-musleabihf.tar.gz"
[[OpenSSL]]
arch = "i686"
git-tree-sha1 = "4394d5795bded42e642ceea036079352912c6760"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "845e9dbf1bced259af5af936cb67de52bcc5d7be3c939fe6ed462457534b53c6"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.i686-linux-gnu.tar.gz"
[[OpenSSL]]
arch = "i686"
git-tree-sha1 = "859b640e692858268a7e2fac91f3faa571447cd0"
libc = "musl"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "11e88ae235e5e570abd41412f7d84bd9f836a9e781eca17d7b142fca3b07a2e1"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.i686-linux-musl.tar.gz"
[[OpenSSL]]
arch = "i686"
git-tree-sha1 = "0594dab2bf1f121f4be2833e83d54b718feb58ad"
os = "windows"

    [[OpenSSL.download]]
    sha256 = "ca19e5e4009406a7130f3a4dea49ecfce6e225730bd46a1b5102f438fba0a2a7"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.i686-w64-mingw32.tar.gz"
[[OpenSSL]]
arch = "powerpc64le"
git-tree-sha1 = "6da7ed7fff69b07d9c0af8dc31486ee8feb2e885"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "e84a34bfd017aee1b6bd377a893e9bd3cf7acce9f9d819f138687360f90cad76"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.powerpc64le-linux-gnu.tar.gz"
[[OpenSSL]]
arch = "riscv64"
git-tree-sha1 = "f80fd2aceb8ce0c75bd229e548f232907054b8f2"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "7a8041b0fea82c925ea05c0a0e29c22edb2cb95d7b162c218b8822fb4fa266f8"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.riscv64-linux-gnu.tar.gz"
[[OpenSSL]]
arch = "x86_64"
git-tree-sha1 = "f59ae8ad1ae3c147a3b22ba08ea5d758ac413027"
os = "macos"

    [[OpenSSL.download]]
    sha256 = "a97bcbf36aeebc04bb083d3596106672ab93c0865aab9113fffa25f1d114ef94"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.x86_64-apple-darwin.tar.gz"
[[OpenSSL]]
arch = "x86_64"
git-tree-sha1 = "2dd587aa4fb3c5d9ed0d51c29461692d6ee25113"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "8e2c75378726017fc66fb7fbbd10fb53522417c3e45a88af77b8853d46f2b063"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.x86_64-linux-gnu.tar.gz"
[[OpenSSL]]
arch = "x86_64"
git-tree-sha1 = "e560bc7bae9152806338732136264ddb87fe630e"
libc = "musl"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "4c01eb9d07ed91a3b3bc0e900b723b36c79cc51df83b4cdda129b4ed08b318c1"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.x86_64-linux-musl.tar.gz"
[[OpenSSL]]
arch = "x86_64"
git-tree-sha1 = "19155b76a654450086cf36ab1c0d0d854d409067"
os = "freebsd"

    [[OpenSSL.download]]
    sha256 = "4d3f8074ed832fd63f689874ca00475bc826862ea44cf57434cd98667a9a329d"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.x86_64-unknown-freebsd.tar.gz"
[[OpenSSL]]
arch = "x86_64"
git-tree-sha1 = "c886d88131e572660c38564d443d1fa09e15140b"
os = "windows"

    [[OpenSSL.download]]
    sha256 = "ed4a10a89f7097309b2c9626b55a4fc0cfca28f262c7f48c7c3cf9f2e69feccd"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v3.5.9+0/OpenSSL.v3.5.9.x86_64-w64-mingw32.tar.gz"
