# Autogenerated wrapper script for OpenSSL_jll for x86_64-apple-darwin
export libcrypto, libssl, openssl

JLLWrappers.@generate_wrapper_header("OpenSSL")
JLLWrappers.@declare_library_product(libcrypto, "@rpath/libcrypto.1.1.dylib")
JLLWrappers.@declare_library_product(libssl, "@rpath/libssl.1.1.dylib")
JLLWrappers.@declare_executable_product(openssl)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcrypto,
        "lib/libcrypto.1.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libssl,
        "lib/libssl.1.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        openssl,
        "bin/openssl",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
